<div class="row-fluid">
    <div class="divPanel">
        <h3>Configuración</h3>
        <div class="divPanelMini">
            <ul>
                <li>
                    <a href="<?php echo $this->url(array('controller'=>'configuracion','action'=>'inicio'),null,true); ?>"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
            </ul>
        </div>
    </div>
    <div class="divPanel">
        <h3>Contenido</h3>
        <div class="divPanelMini">
            <ul>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/articulo.png"></img>
                    <p>Articulos</p>
                    </a>
                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/normas.png"></img>
                    <p>Normas Legales</p>
                    </a>
                    
                </li>
            </ul>
        </div>
    </div>
    <div class="divPanel">
        <h3>Marketing</h3>
        <div class="divPanelMini">
            <ul>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/encuesta.png"></img>
                    <p>Encuestas</p>
                    </a>
                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
            </ul>
        </div>
    </div>
    <div class="divPanel">
        <h3>Administración</h3>
        <div class="divPanelMini">
            <ul>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/home.png"></img>
                    <p>Página Inicio</p>
                    </a>
                    
                </li>
            </ul>
        </div>
    </div>
</div>