<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>CMS ADMIN</title>
        <meta name="description" content="">
        <meta name="author" content="">
        <link href="<?php echo $this->baseUrl() ?>/css/estilo_admin.css" rel="stylesheet"></link>
        
        <script src="<?php echo $this->baseUrl() ?>/js/modernizr.js" type="text/javascript" charset="utf-8"></script>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>
